{
	"assessmentTaker": {
		"assessmentId": "ab71286e-fe9c-4b66-b5ea-d060377b3fbf",
		"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
		"id": "59e04b4c-fea0-4a66-8f5b-b675c52fa83c",
		"assessmentName": "Taking Assessment Part 2",
		"dispatcher": "9e1d8324-ea29-43b8-bc85-4abb78bfbc82",
		"showResults": true,
		"email": "sandra.kumi@amalitech.com",
		"assessmentLink": "https://amap-staging.amalitech-dev.net/test-taker/system-instruction?organizationId=1bf5694a-8452-4811-818f-dc6293f634ad&assessmentId=ab71286e-fe9c-4b66-b5ea-d060377b3fbf&testTakerId=59e04b4c-fea0-4a66-8f5b-b675c52fa83c",
		"assessmentWindowViolationCount": 0,
		"assessmentWindowViolationDuration": 0,
		"assessmentTakerShotCount": 0,
		"assessmentTakerViolationShotCount": 0,
		"windowShotCount": 0,
		"windowViolationShotCount": 0,
		"assessmentDuration": 55,
		"estimatedEndTime": null,
		"expireDate": "2025-05-23T03:49:00.000Z",
		"commenceDate": "2025-05-21T15:51:57.009Z",
		"startTime": null,
		"endTime": null,
		"proctor": null,
		"conductSurvey": false,
		"screenshotsInterval": 15,
		"camerashotsInterval": 15,
		"testList": [
			"91642bfc-1ea9-475e-b6c2-8f7f5a2b6680",
			"b5bc5e0c-2d36-4025-8e02-6e2e09d59aa4",
			"bcbd9034-cd66-49cc-bc4d-8e663553809a"
		],
		"submittedTests": [],
		"phase": "CODE_CONDUCT_SIGNING",
		"linkStatus": "VALID",
		"status": "In progress",
		"logSummary": [
			"LINK_VIEW"
		],
		"createdAt": "2025-05-21T15:52:33.851Z",
		"updatedAt": "2025-05-21T15:52:33.851Z",
		"reportCallbackURL": null,
		"assessment": {
			"id": "ab71286e-fe9c-4b66-b5ea-d060377b3fbf",
			"title": "Taking Assessment Part 2",
			"instructions": "<p>Read&nbsp;instruction&nbsp;carefully.</p>",
			"showClock": true,
			"conductSurvey": false,
			"screenshotsInterval": null,
			"camerashotsInterval": null,
			"duration": 2700,
			"isDispatched": true,
			"system": true,
			"attempted": true,
			"createdAt": "2025-05-02T09:11:21.553Z",
			"updatedAt": "2025-05-21T15:51:57.051Z",
			"proctor": null,
			"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
			"testOrder": [
				"91642bfc-1ea9-475e-b6c2-8f7f5a2b6680",
				"b5bc5e0c-2d36-4025-8e02-6e2e09d59aa4",
				"bcbd9034-cd66-49cc-bc4d-8e663553809a",
				"91642bfc-1ea9-475e-b6c2-8f7f5a2b6680",
				"b5bc5e0c-2d36-4025-8e02-6e2e09d59aa4",
				"bcbd9034-cd66-49cc-bc4d-8e663553809a"
			],
			"hash": "3196e5a511f32d02773145cba1b3cbfb9bd8538d56ab378234d1343cbb7095b0",
			"passMark": 20,
			"tags": [],
			"Survey": [],
			"tests": [
				{
                                        "id": "91642bfc-1ea9-475e-b6c2-8f7f5a2b6680",
					"title": "Multi-Select Test",
					"isActivated": true,
					"system": true,
					"useDomainQuestions": false,
					"passMark": 50,
					"noOfQuestions": 4,
					"description": "<p>None</p>",
					"instructions": "<p>None</p>",
					"passage": null,
					"duration": 31,
					"difficultyLevel": "Beginner",
					"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
					"createdAt": "2025-02-28T07:43:17.144Z",
					"updatedAt": "2025-05-02T09:12:10.845Z",
					"domainId": "ad6712e8-cca2-47ea-8631-faed07c84c32",
					"type": "regular",
					"hash": "80164422460df51d853ff19dadebc2abd8e908585a315ea0b6a67629ac16e5b8",
					"questions": [
						{
							"id": "15890ee0-f8b0-450d-89bc-55d30a362bae",
							"questionText": "<p>How many are these types of IT Tools</p>",
							"questionTitle": null,
							"isComprehension": false,
							"questionType": "Multi_select",
							"score": 2,
							"creator": null,
							"createdAt": "2024-10-31T12:10:33.013Z",
							"updatedAt": "2025-05-02T09:12:10.845Z",
							"categoryId": "ac4d85c8-2327-4ce5-b5a4-60d0ea02fe5a",
							"domainId": "ad6712e8-cca2-47ea-8631-faed07c84c32",
							"system": true,
							"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
							"timeLimit": null,
							"isActive": true,
							"difficultyLevel": "Beginner",
							"strictMark": true,
							"hash": "25ba7138ae640b2f052e8575d114e1f1fc22aad799ce36640af5954a531cc9fd",
							"multipleChoiceAnswer": null,
							"trueOrFalseAnswer": null,
							"multipleSelectAnswer": {
								"id": "a5727400-b956-45f0-af94-6447fcf7ee86",
								"questionId": "15890ee0-f8b0-450d-89bc-55d30a362bae",
								"options": [
									"8<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"6<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"12<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"9<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->"
								],
							},
							"essayAnswer": null,
							"fillInAnswer": null,
							"matchMatrixAnswer": null,
							"category":  "Quantitative Methods",
							"codeTemplates": [],
							"CodeConstraint": null,
							"questionId": "15890ee0-f8b0-450d-89bc-55d30a362bae",
						},
						{
							"id": "9b542b83-d7f7-420d-80c1-875f894dad79",
							"questionText": "<p>How many are these types of software?</p>",
							"questionTitle": null,
							"isComprehension": false,
							"questionType": "Multi_select",
							"score": 1,
							"creator": null,
							"createdAt": "2024-11-01T10:33:43.796Z",
							"updatedAt": "2025-05-02T09:12:10.845Z",
							"categoryId": "ac4d85c8-2327-4ce5-b5a4-60d0ea02fe5a",
							"domainId": "ad6712e8-cca2-47ea-8631-faed07c84c32",
							"system": true,
							"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
							"timeLimit": null,
							"isActive": true,
							"difficultyLevel": "Beginner",
							"strictMark": true,
							"hash": "0d36dc3a4527f7f37cc4e028f332cab76c6fcaa94b8b2c2562e87404a8037a6a",
							"multipleChoiceAnswer": null,
							"trueOrFalseAnswer": null,
							"multipleSelectAnswer": {
								"id": "fa3e10b7-8469-45da-85a3-5b785c6701af",
								"questionId": "9b542b83-d7f7-420d-80c1-875f894dad79",
								"options": [
									"4<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"3<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"2<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"5<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->"
								],
							},
							"essayAnswer": null,
							"fillInAnswer": null,
							"matchMatrixAnswer": null,
							"category": "Quantitative Methods",
							"codeTemplates": [],
							"CodeConstraint": null,
							"questionId": "9b542b83-d7f7-420d-80c1-875f894dad79",
						},
						{
							"id": "4b8f3bdc-25d6-4ee8-a163-6e5445dea491",
							"questionText": "<p>                                           hhjjjj</p>",
							"questionTitle": null,
							"isComprehension": false,
							"questionType": "Multi_select",
							"score": 5,
							"creator": null,
							"createdAt": "2024-10-21T11:34:27.238Z",
							"updatedAt": "2025-05-02T09:12:10.845Z",
							"categoryId": "8321dad4-4248-4c7c-8928-3b79f5080d38",
							"domainId": "ad6712e8-cca2-47ea-8631-faed07c84c32",
							"system": true,
							"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
							"timeLimit": null,
							"isActive": true,
							"difficultyLevel": "Advanced",
							"strictMark": true,
							"hash": "1f33c976a88f2e7909a1343484d2dab151a34971a7d4680ceba5a358000a1802",
							"multipleChoiceAnswer": null,
							"trueOrFalseAnswer": null,
							"multipleSelectAnswer": {
								"id": "bae90756-7e80-4a95-b793-66a37618ee7f",
								"questionId": "4b8f3bdc-25d6-4ee8-a163-6e5445dea491",
								"options": [
									"&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bbbbbbbbbbb<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"vvvvvvvvvvvvvvvvv<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"bggggggggggggg<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"ggggggggggggggggggg<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->"
								],
															},
							"essayAnswer": null,
							"fillInAnswer": null,
							"matchMatrixAnswer": null,
							"category": "Logic Reasoning",
							"codeTemplates": [],
							"CodeConstraint": null,
							"questionId": "4b8f3bdc-25d6-4ee8-a163-6e5445dea491",
						},
						{
							"id": "ab5630bb-8d34-4662-bf87-89e0a97f488f",
							"questionText": "<p><span style=\"background-color: rgb(255, 255, 255); color: rgba(6, 8, 31, 0.88);\">Which&nbsp;of&nbsp;the&nbsp;following&nbsp;are&nbsp;programming&nbsp;languages?</span></p>",
							"questionTitle": null,
							"isComprehension": false,
							"questionType": "Multi_select",
							"score": 5,
							"creator": null,
							"createdAt": "2025-02-26T16:50:45.872Z",
							"updatedAt": "2025-05-02T09:12:10.845Z",
							"categoryId": "8321dad4-4248-4c7c-8928-3b79f5080d38",
							"domainId": "ad6712e8-cca2-47ea-8631-faed07c84c32",
							"system": true,
							"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
							"timeLimit": null,
							"isActive": true,
							"difficultyLevel": "Beginner",
							"strictMark": false,
							"hash": "7b3f8c54e5e4fcdadcc96debb3c5b90a53f373907218aa68184d26a0eb28f83b",
							"multipleChoiceAnswer": null,
							"trueOrFalseAnswer": null,
							"multipleSelectAnswer": {
								"id": "0c62b3c3-bc58-4b3d-bbef-3b7373897687",
								"questionId": "ab5630bb-8d34-4662-bf87-89e0a97f488f",
								"options": [
									"<ul style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-bottom: 20px; padding-inline-start: 1.15em; color: rgba(6, 8, 31, 0.88); font-family: D-DINExp, &quot;DM Sans&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px;\"><li style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ;\">A) Python</li></ul><span class=\"placeholder absolute top-2 left-3 text-gray-400 ng-star-inserted\">  </span><!----><!---->",
									"<ul style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-bottom: 20px; padding-inline-start: 1.15em; color: rgba(6, 8, 31, 0.88); font-family: D-DINExp, &quot;DM Sans&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px;\"><li style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-top: 0.25em;\">B) HTML</li></ul><span class=\"placeholder absolute top-2 left-3 text-gray-400 ng-star-inserted\">  </span><!----><!---->",
									"<ul style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-bottom: 20px; padding-inline-start: 1.15em; color: rgba(6, 8, 31, 0.88); font-family: D-DINExp, &quot;DM Sans&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px;\"><li style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-top: 0.25em;\">C) Java</li></ul><span class=\"placeholder absolute top-2 left-3 text-gray-400 ng-star-inserted\">  </span><!----><!---->",
									"<ul style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-bottom: 20px; padding-inline-start: 1.15em; color: rgba(6, 8, 31, 0.88); font-family: D-DINExp, &quot;DM Sans&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px;\"><li style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-top: 0.25em;\">D) CSS</li></ul><span class=\"placeholder absolute top-2 left-3 text-gray-400 ng-star-inserted\">  </span><!----><!---->"
								],
														},
							"essayAnswer": null,
							"fillInAnswer": null,
							"matchMatrixAnswer": null,
							"category": "Logic Reasoning",
							"codeTemplates": [],
							"CodeConstraint": null,
							"questionId": "ab5630bb-8d34-4662-bf87-89e0a97f488f",
						}
					],
					"domain": "Aptitude"
					},
				{
					"title": "Test for Practice",
					"isActivated": true,
					"system": true,
					"useDomainQuestions": false,
					"passMark": 20,
					"noOfQuestions": 3,
					"description": "<p>test&nbsp;functionality</p>",
					"instructions": "<p>test&nbsp;functionality</p>",
					"passage": null,
					"duration": 300,
					"difficultyLevel": "Beginner",
					"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
					"createdAt": "2025-04-07T15:52:29.492Z",
					"updatedAt": "2025-05-02T09:13:34.662Z",
					"domainId": "55e72c01-8dcd-4e74-b431-98a76d951236",
					"type": "regular",
					"hash": "b0b5c72fec15f99d1a120d92f10d0c8c7f934d1c8f0b8cb70cc84af984025faa",
					"questions": [
						{
							"id": "cf783856-0a25-440c-a647-3cba38340da2",
							"questionText": "Water freezes at 0 C (32 F).",
							"questionTitle": null,
							"isComprehension": false,
							"questionType": "True_or_false",
							"score": 1,
							"creator": null,
							"createdAt": "2025-04-07T15:26:09.883Z",
							"updatedAt": "2025-05-02T09:13:34.662Z",
							"categoryId": "a84ae68d-715a-432e-94a0-c835e6706fc1",
							"domainId": "55e72c01-8dcd-4e74-b431-98a76d951236",
							"system": true,
							"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
							"timeLimit": null,
							"isActive": true,
							"difficultyLevel": "Advanced",
							"strictMark": null,
							"hash": "bae937c0cebc43cb6b8f5b5e7d123c5c20db539e295a445b05a81b5926f4728d",
							"multipleChoiceAnswer": null,
							"trueOrFalseAnswer": {
								"id": "ba9b0f59-f7d7-4071-8a6e-8cef20c29ca1",
								"questionId": "cf783856-0a25-440c-a647-3cba38340da2",
								"options": [
									"True",
									"False"
								],
							},
							"multipleSelectAnswer": null,
							"essayAnswer": null,
							"fillInAnswer": null,
							"matchMatrixAnswer": null,
							"category": "Extended family",
							"codeTemplates": [],
							"CodeConstraint": null,
							"questionId": "cf783856-0a25-440c-a647-3cba38340da2",
						},
						{
							"id": "052495b2-eb03-43ff-b54c-aa554b079076",
							"questionText": "The Earth is the third planet from the moon",
							"questionTitle": null,
							"isComprehension": false,
							"questionType": "True_or_false",
							"score": 1,
							"creator": null,
							"createdAt": "2025-04-07T15:28:08.486Z",
							"updatedAt": "2025-05-02T09:13:34.662Z",
							"categoryId": "a84ae68d-715a-432e-94a0-c835e6706fc1",
							"domainId": "55e72c01-8dcd-4e74-b431-98a76d951236",
							"system": true,
							"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
							"timeLimit": null,
							"isActive": true,
							"difficultyLevel": "Intermediate",
							"strictMark": null,
							"hash": "87899b6f74a01cc25ea06dc73134fba2c9dbdad3076929f7a64e90dfd3c3200f",
							"multipleChoiceAnswer": null,
							"trueOrFalseAnswer": {
								"id": "ce149abb-3502-4b9c-8fd3-38faca18f599",
								"questionId": "052495b2-eb03-43ff-b54c-aa554b079076",
								"options": [
									"True",
									"False"
								],
							},
							"multipleSelectAnswer": null,
							"essayAnswer": null,
							"fillInAnswer": null,
							"matchMatrixAnswer": null,
							"category":  "Extended family"
							,
							"codeTemplates": [],
							"CodeConstraint": null,
							"idleTime": 0,
							"questionId": "052495b2-eb03-43ff-b54c-aa554b079076",
													},
						{
							"id": "505fe237-2dba-4bb4-96ec-d59953a25f4a",
							"questionText": "The Earth is the third planet from the Sun.",
							"questionTitle": null,
							"isComprehension": false,
							"questionType": "True_or_false",
							"score": 1,
							"creator": null,
							"createdAt": "2025-04-07T15:26:09.905Z",
							"updatedAt": "2025-05-02T09:13:34.662Z",
							"categoryId": "a84ae68d-715a-432e-94a0-c835e6706fc1",
							"domainId": "55e72c01-8dcd-4e74-b431-98a76d951236",
							"system": true,
							"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
							"timeLimit": null,
							"isActive": true,
							"difficultyLevel": "Intermediate",
							"strictMark": null,
							"hash": "af349ecd773fcd93467cc3a3eeb7e3de971b53c4c53f5fcf1933a79c6966a45e",
							"multipleChoiceAnswer": null,
							"trueOrFalseAnswer": {
								"id": "92771c67-4ea4-4834-b4b2-fdad6b671ef7",
								"questionId": "505fe237-2dba-4bb4-96ec-d59953a25f4a",
								"options": [
									"True",
									"False"
								],
							},
							"multipleSelectAnswer": null,
							"essayAnswer": null,
							"fillInAnswer": null,
							"matchMatrixAnswer": null,
							"category": "Extended family"
							,
							"codeTemplates": [],
							"questionId": "505fe237-2dba-4bb4-96ec-d59953a25f4a",
						}
					],
                                        "domain": "Social Studies"
					},
				{
                                        "id": "bcbd9034-cd66-49cc-bc4d-8e663553809a",
					"title": "Multi Select Question",
					"isActivated": true,
					"system": true,
					"useDomainQuestions": false,
					"passMark": 100,
					"noOfQuestions": 3,
					"description": "<p>test multi select question</p>",
					"instructions": "<p>test multi select question</p>",
					"passage": null,
					"duration": 14,
					"difficultyLevel": "Beginner",
					"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
					"createdAt": "2025-03-22T14:47:04.219Z",
					"updatedAt": "2025-05-02T09:12:10.845Z",
					"domainId": "ad6712e8-cca2-47ea-8631-faed07c84c32",
					"type": "regular",
					"hash": "54f0493e6fe4995a932819305d5db5ebb38c757c73c033ef612a93784f5cf616",
					"questions": [
						{
							"id": "15890ee0-f8b0-450d-89bc-55d30a362bae",
							"questionText": "<p>How many are these types of IT Tools</p>",
							"questionTitle": null,
							"isComprehension": false,
							"questionType": "Multi_select",
							"score": 2,
							"creator": null,
							"createdAt": "2024-10-31T12:10:33.013Z",
							"updatedAt": "2025-05-02T09:12:10.845Z",
							"categoryId": "ac4d85c8-2327-4ce5-b5a4-60d0ea02fe5a",
							"domainId": "ad6712e8-cca2-47ea-8631-faed07c84c32",
							"system": true,
							"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
							"timeLimit": null,
							"isActive": true,
							"difficultyLevel": "Beginner",
							"strictMark": true,
							"hash": "25ba7138ae640b2f052e8575d114e1f1fc22aad799ce36640af5954a531cc9fd",
                                                        "domain": "Aptitude",
							"category": "Quantitative Methods",
							"multipleChoiceAnswer": null,
							"trueOrFalseAnswer": null,
							"multipleSelectAnswer": {
								"id": "a5727400-b956-45f0-af94-6447fcf7ee86",
								"questionId": "15890ee0-f8b0-450d-89bc-55d30a362bae",
								"options": [
									"8<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"6<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"12<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"9<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->"
								],
							},
							"essayAnswer": null,
							"fillInAnswer": null,
							"matchMatrixAnswer": null,
							"category": {
								"name": "Quantitative Methods"
							},
							"codeTemplates": [],
							"CodeConstraint": null,
							"questionId": "15890ee0-f8b0-450d-89bc-55d30a362bae",
						},
						{
							"id": "ab5630bb-8d34-4662-bf87-89e0a97f488f",
							"questionText": "<p><span style=\"background-color: rgb(255, 255, 255); color: rgba(6, 8, 31, 0.88);\">Which&nbsp;of&nbsp;the&nbsp;following&nbsp;are&nbsp;programming&nbsp;languages?</span></p>",
							"questionTitle": null,
							"isComprehension": false,
							"questionType": "Multi_select",
							"score": 5,
							"creator": null,
							"createdAt": "2025-02-26T16:50:45.872Z",
							"updatedAt": "2025-05-02T09:12:10.845Z",
							"categoryId": "8321dad4-4248-4c7c-8928-3b79f5080d38",
							"domainId": "ad6712e8-cca2-47ea-8631-faed07c84c32",
							"system": true,
							"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
							"timeLimit": null,
							"isActive": true,
							"difficultyLevel": "Beginner",
							"strictMark": false,
							"hash": "7b3f8c54e5e4fcdadcc96debb3c5b90a53f373907218aa68184d26a0eb28f83b",
							"multipleChoiceAnswer": null,
							"trueOrFalseAnswer": null,
							"multipleSelectAnswer": {
								"id": "0c62b3c3-bc58-4b3d-bbef-3b7373897687",
								"questionId": "ab5630bb-8d34-4662-bf87-89e0a97f488f",
								"options": [
									"<ul style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-bottom: 20px; padding-inline-start: 1.15em; color: rgba(6, 8, 31, 0.88); font-family: D-DINExp, &quot;DM Sans&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px;\"><li style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ;\">A) Python</li></ul><span class=\"placeholder absolute top-2 left-3 text-gray-400 ng-star-inserted\">  </span><!----><!---->",
									"<ul style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-bottom: 20px; padding-inline-start: 1.15em; color: rgba(6, 8, 31, 0.88); font-family: D-DINExp, &quot;DM Sans&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px;\"><li style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-top: 0.25em;\">B) HTML</li></ul><span class=\"placeholder absolute top-2 left-3 text-gray-400 ng-star-inserted\">  </span><!----><!---->",
									"<ul style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-bottom: 20px; padding-inline-start: 1.15em; color: rgba(6, 8, 31, 0.88); font-family: D-DINExp, &quot;DM Sans&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px;\"><li style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-top: 0.25em;\">C) Java</li></ul><span class=\"placeholder absolute top-2 left-3 text-gray-400 ng-star-inserted\">  </span><!----><!---->",
									"<ul style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-bottom: 20px; padding-inline-start: 1.15em; color: rgba(6, 8, 31, 0.88); font-family: D-DINExp, &quot;DM Sans&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px;\"><li style=\"--tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; margin-top: 0.25em;\">D) CSS</li></ul><span class=\"placeholder absolute top-2 left-3 text-gray-400 ng-star-inserted\">  </span><!----><!---->"
								],
							},
							"essayAnswer": null,
							"fillInAnswer": null,
							"matchMatrixAnswer": null,
							"category": "Logic Reasoning"
							,
							"codeTemplates": [],
							"CodeConstraint": null,
							"questionId": "ab5630bb-8d34-4662-bf87-89e0a97f488f",
													},
						{
							"id": "9b542b83-d7f7-420d-80c1-875f894dad79",
							"questionText": "<p>How many are these types of software?</p>",
							"questionTitle": null,
							"isComprehension": false,
							"questionType": "Multi_select",
							"score": 1,
							"creator": null,
							"createdAt": "2024-11-01T10:33:43.796Z",
							"updatedAt": "2025-05-02T09:12:10.845Z",
							"categoryId": "ac4d85c8-2327-4ce5-b5a4-60d0ea02fe5a",
							"domainId": "ad6712e8-cca2-47ea-8631-faed07c84c32",
							"system": true,
							"organizationId": "1bf5694a-8452-4811-818f-dc6293f634ad",
							"timeLimit": null,
							"isActive": true,
							"difficultyLevel": "Beginner",
							"strictMark": true,
							"hash": "0d36dc3a4527f7f37cc4e028f332cab76c6fcaa94b8b2c2562e87404a8037a6a",
							"multipleChoiceAnswer": null,
							"trueOrFalseAnswer": null,
							"multipleSelectAnswer": {
								"id": "fa3e10b7-8469-45da-85a3-5b785c6701af",
								"questionId": "9b542b83-d7f7-420d-80c1-875f894dad79",
								"options": [
									"4<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"3<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"2<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->",
									"5<span class=\"placeholder absolute top-2 left-3 text-gray-400\">  </span><!----><!---->"
								],							},
							"essayAnswer": null,
							"fillInAnswer": null,
							"matchMatrixAnswer": null,
							"category": "Quantitative Methods"
							,
							"codeTemplates": [],
							"CodeConstraint": null,

						}
					],
                                    "domain": "Aptitude"
				}
			],
			"proctorFeatures": [
				{
					"id": "4986ac57-3f94-47d2-bda3-4ba3d9d9f0a1",
					"name": "Honour Code",
					"description": "The user is required to sign an honor code.",
					"createdAt": "2024-08-27T16:39:06.271Z",
					"updatedAt": "2024-08-27T16:39:06.271Z"
				}
			],
			"assessmentDuration": 3300,
			"assessmentStartTime": "2025-05-21T15:53:08.760Z"
		},
		"currentDate": "2025-05-21T15:53:08.760Z"
	},
	"seconds": 3300
}